services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravelEvaluation:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    expose:
      - "9000"
    ports:
      - "8081:9000"
    volumes:
      - ./laravelEvaluation:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy  # Wait for MySQL to be ready

  mysql:
    build:
      context: ./docker/mysql
    platform: linux/x86_64
    ports:
      - "3307:3306"  # Host:Container
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravelevaluation
      MYSQL_USER: laravel  # Optional: create a non-root user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local